<?php

namespace Database\Seeders;

use App\Models\TipoPago;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TipoPagoSeeder extends Seeder
{
  public function run(): void
  {
    // 1. Desactivamos claves foráneas para poder limpiar sin errores
    // 1. Desactivamos claves foráneas para poder limpiar sin errores
    // Schema::disableForeignKeyConstraints();

    // 2. Limpiamos la tabla
    // DB::table('tipos_pago')->truncate();

    // 3. Reactivamos claves foráneas
    // Schema::enableForeignKeyConstraints();

    // 4. Definimos los datos
    $tiposPago = [
      [
        'id' => 4,
        'nombre' => 'Puntos Efecty',
        'enlace' => '7709998132481',
        'activo' => true,
        'imagen' => 'efecty.png',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => '<b>*</b> Puede realizar el pago en Efecty <b style="font-size: 10px">*</b> este pago no será reembolsable, en caso de no asistir al evento se ingresará bajo el concepto de ofrenda general <b style="font-size: 10px">*</b> Este pago está sujeto a términos y condiciones, para mayor información consúltenos en: soymanantial.com',
        'habilitado_punto_pago' => false,
        'subir_archivo_pagos' => true,
        'botones_valores_moneda' => false,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => null,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => 'efecty',
        'account_id' => null,
        'habilitado_donacion' => false,
        'transaccion_minima' => null,
        'transaccion_maxima' => null,
      ],
      [
        'id' => 3,
        'nombre' => 'Grupo Éxito',
        'enlace' => '0000000020080',
        'activo' => true,
        'imagen' => 'exito.png',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => 'Puede realizar el pago en cualquier punto de pago del Grupo Éxito (Surtimax, Carulla, Pomona, Almacenes Éxito, Super Inter) y cualquier oficina de Banco de Occidente S.A.<b style="font-size: 10px">*</b> Este pago no será reembolsable, en caso de no asistir al evento se ingresará bajo el concepto de ofrenda general.<b style="font-size:10px">*</b> Este pago está sujeto a términos y condiciones, para mayor información soymanantial.com',
        'habilitado_punto_pago' => false,
        'subir_archivo_pagos' => true,
        'botones_valores_moneda' => false,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => null,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => '1',
        'account_id' => null,
        'habilitado_donacion' => false,
        'transaccion_minima' => null,
        'transaccion_maxima' => null,
      ],
      [
        'id' => 5,
        'nombre' => 'Efectivo (PDP)',
        'enlace' => '',
        'activo' => true,
        'imagen' => '',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => '',
        'habilitado_punto_pago' => true,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => true,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => 1,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => '1',
        'account_id' => null,
        'habilitado_donacion' => false,
        'transaccion_minima' => null,
        'transaccion_maxima' => null,
      ],
      [
        'id' => 7,
        'nombre' => 'Tarjeta Débito (PDP)',
        'enlace' => '',
        'activo' => true,
        'imagen' => '',
        'created_at' => '2019-02-07 17:44:30',
        'updated_at' => '2019-02-07 17:44:30',
        'cuenta_sap' => '',
        'observaciones' => '.',
        'habilitado_punto_pago' => true,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => false,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => null,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => '1',
        'account_id' => null,
        'habilitado_donacion' => false,
        'transaccion_minima' => null,
        'transaccion_maxima' => null,
      ],
      [
        'id' => 8,
        'nombre' => 'Paypal',
        'enlace' => 'https://www.sandbox.paypal.com',
        'activo' => true,
        'imagen' => 'paypal.png',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => 'Este método de pago solo esta habilitado para pagos por tarjeta de crédito. su cuenta de Paypal debe estar registrada fuera de Colombia..',
        'habilitado_punto_pago' => false,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => false,
        'client_id' => 'AeXnDVIPUIihwL5mIXrrrqwRlphe79QAAhhu3ieeAN77hxTkVlDtI7MH3791_ChSDrJIGZPogt56oX4B',
        'key_id' => 'EEJiKQyAC475y-hUmWCnWLPvHD-u7H43xdg_GQD6baVNxVkuZxD0ZLHS6yjSItSRx-Mhr1z-RGh0-MT7',
        'bussines_id' => 'sb-0rf2116423789@business.example.com',
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => 2,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => 'paypal',
        'account_id' => null,
        'habilitado_donacion' => false,
        'transaccion_minima' => 1,
        'transaccion_maxima' => 9999,
      ],
      [
        'id' => 9,
        'nombre' => 'Payu Colombia',
        'enlace' => 'https://checkout.payulatam.com/ppp-web-gateway-payu/',
        'activo' => false,
        'imagen' => 'payu.png',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => 'Pasarela de pago configurada para colombia',
        'habilitado_punto_pago' => false,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => false,
        'client_id' => 'mEzl5b4Q1DsrA8C',
        'key_id' => 'v8WocoF72DEFuYd3089y1l4QFO',
        'bussines_id' => '559978',
        'url_retorno' => null,
        'identity_token' => 'PKg6j4QV4002doSU1386RSl05w',
        'unica_moneda_id' => 1,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => 'payu',
        'account_id' => '562463',
        'habilitado_donacion' => false,
        'transaccion_minima' => 10000,
        'transaccion_maxima' => 30000000,
      ],
      [
        'id' => 1,
        'nombre' => 'Pagos por Internet',
        'enlace' => 'https://www.zonapagos.com/ws_inicio_pagov2/Zpagos.asmx?wsdl',
        'activo' => true,
        'imagen' => 'zonapagos.png',
        'created_at' => '2013-09-26 22:03:37',
        'updated_at' => '2013-09-26 22:03:37',
        'cuenta_sap' => '11050513',
        'observaciones' => '1',
        'habilitado_punto_pago' => false,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => false,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => 1,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => 'zona',
        'account_id' => null,
        'habilitado_donacion' => true,
        'transaccion_minima' => 999,
        'transaccion_maxima' => 30000000,
      ],
      [
        'id' => 6,
        'nombre' => 'Tarjeta de Crédito',
        'enlace' => '',
        'activo' => true,
        'imagen' => '',
        'created_at' => '2019-02-07 17:44:30',
        'updated_at' => '2019-02-07 17:44:30',
        'cuenta_sap' => '',
        'observaciones' => '.',
        'habilitado_punto_pago' => true,
        'subir_archivo_pagos' => false,
        'botones_valores_moneda' => false,
        'client_id' => null,
        'key_id' => null,
        'bussines_id' => null,
        'url_retorno' => null,
        'identity_token' => null,
        'unica_moneda_id' => null,
        'porcentaje_tax1' => null,
        'porcentaje_tax2' => null,
        'key_reservada' => '1',
        'account_id' => null,
        'habilitado_donacion' => true,
        'transaccion_minima' => 100,
        'transaccion_maxima' => null,
      ],
    ];


    // CORRECCIÓN: Usar insert() en lugar de create()
    foreach ($tiposPago as $pago) {
      TipoPago::firstOrCreate(
        ['id' => $pago['id']],
        $pago
      );
    }

    // Opcional: Si usas PostgreSQL y necesitas reiniciar el autoincrement
    // if (DB::getDriverName() == 'pgsql') {
    //   DB::statement("SELECT setval('tipos_pago_id_seq', (SELECT MAX(id) FROM tipos_pago));");
    // }
  }
}
