
INSERT INTO "campos_informe_excel" ("id", "nombre_campo_bd", "nombre_campo_informe", "selector_id", "tabla", "raw_sql", "eloquent_sql", "orden") VALUES
(62,	'grupo_id',	'Grupo directo',	5,	'asistentes.',	't',	'f',	62),
(1,	'tipo_identificacion',	'Tipo de identificación',	1,	'asistentes.',	't',	'f',	1),
(2,	'identificacion',	'Identificación',	1,	'asistentes.',	't',	'f',	2),
(6,	'segundo_nombre',	'Segundo nombre',	1,	'asistentes.',	't',	'f',	5),
(5,	'primer_nombre',	'Primer nombre',	1,	'asistentes.',	't',	'f',	4),
(8,	'primer_apellido',	'Primer apellido',	1,	'asistentes.',	't',	'f',	6),
(9,	'segundo_apellido',	'Segundo apellido',	1,	'asistentes.',	't',	'f',	7),
(10,	'estado_civil',	'Estado civil',	1,	'asistentes.',	't',	'f',	8),
(11,	'pais_id',	'País de nacimiento',	1,	'asistentes.',	't',	'f',	9),
(12,	'telefono_fijo',	'Teléfono fijo',	1,	'asistentes.',	't',	'f',	10),
(45,	'telefono_otro',	'Otro teléfono',	1,	'asistentes.',	't',	'f',	11),
(13,	'telefono_movil',	'Teléfono móvil',	1,	'asistentes.',	't',	'f',	12),
(14,	'email',	'E-mail',	1,	'users.',	'f',	't',	13),
(15,	'direccion',	'Dirección',	1,	'asistentes.',	't',	'f',	14),
(16,	'tipo_vivienda',	'Vivienda en calidad de',	1,	'asistentes.',	't',	'f',	15),
(17,	'nivel_academico',	'Nivel académico',	1,	'asistentes.',	't',	'f',	16),
(18,	'estado_nivel_academico',	'Estado nivel académico',	1,	'asistentes.',	't',	'f',	17),
(19,	'profesion',	'Profesión',	1,	'asistentes.',	't',	'f',	18),
(20,	'sector_economico',	'Sector económico',	1,	'asistentes.',	't',	'f',	19),
(21,	'tipo_sangre',	'Tipo de sangre',	1,	'asistentes.',	't',	'f',	20),
(22,	'indicaciones_medicas',	'Indicaciones médicas',	1,	'asistentes.',	't',	'f',	21),
(31,	'nombre',	'Nombre',	5,	'grupos.',	't',	'f',	34),
(32,	'fecha_apertura',	'Fecha de creación',	5,	'grupos.',	't',	'f',	37),
(33,	'tipo_vivienda',	'Vivienda en calidad De',	5,	'grupos.',	't',	'f',	38),
(34,	'direccion',	'Dirección',	5,	'grupos.',	't',	'f',	39),
(35,	'telefono',	'Teléfono',	5,	'grupos.',	't',	'f',	40),
(36,	'dia',	'Día',	5,	'grupos.',	't',	'f',	41),
(37,	'hora',	'Hora',	5,	'grupos.',	't',	'f',	42),
(38,	'dia_planeacion',	'Dia planeación',	5,	'grupos.',	't',	'f',	43),
(39,	'hora_planeacion',	'Hora planeación',	5,	'grupos.',	't',	'f',	44),
(40,	'encargados',	'Encargados',	5,	'encargados_grupo.',	'f',	't',	45),
(41,	'fecha',	'Fecha ultimo reporte',	5,	'grupos.',	'f',	't',	46),
(42,	'latitud',	'Georreferencia realizada',	5,	'grupos.',	't',	'f',	47),
(44,	'sede_id',	'Sede',	5,	'grupos.',	't',	'f',	48),
(43,	'cantidad_asistentes',	'Cantidad asistentes directos',	5,	'asistentes.',	'f',	't',	49),
(46,	'dado_alta',	'Motivo dado alta',	1,	'null.',	NULL,	NULL,	23),
(47,	'dado_baja',	'Motivo dado baja',	1,	'null.',	NULL,	NULL,	24),
(48,	'fecha_dado_alta',	'Fecha dado alta',	1,	'null.',	NULL,	NULL,	25),
(49,	'fecha_dado_baja',	'Fecha dado baja',	1,	'null.',	NULL,	NULL,	26),
(54,	'contacto_adulto_responsable',	'Contacto adulto responsable',	1,	'asistentes.',	'f',	't',	28),
(55,	'nombre_acudiente',	'Nombre acudiente',	1,	'asistentes.',	't',	'f',	29),
(56,	'telefono_acudiente',	'Contacto acudiente',	1,	'asistentes.',	't',	'f',	30),
(52,	'edad',	'Edad',	1,	'asistentes.',	'f',	't',	3),
(3,	'fecha_nacimiento',	'Fecha nacimiento',	1,	'asistentes.',	't',	'f',	33),
(50,	'genero',	'Sexo',	1,	'asistentes.',	't',	'f',	34),
(29,	'fecha',	'Fecha de los procesos',	4,	'crecimiento_asistentes.',	't',	'f',	60),
(30,	'detalle',	'Detalle de los procesos',	4,	'crecimiento_asistentes.',	'f',	't',	61),
(28,	'estado',	'Estados de los proceso',	4,	'crecimiento_asistentes.',	'f',	't',	62),
(58,	'ultimo_reporte_grupo',	'Última asistencia a grupo',	1,	'asistentes.',	't',	'f',	35),
(59,	'ultimo_reporte_reunion',	'Última asistencia a reunión',	1,	'asistentes.',	't',	'f',	36),
(24,	'tipo_vinculacion_id',	'Tipo de vinculación',	2,	'asistentes.',	't',	'f',	37),
(25,	'tipo_asistente_id',	'Tipo de asistente',	2,	'asistentes.',	't',	'f',	38),
(27,	'sede_id',	'Sede',	2,	'asistentes.',	't',	'f',	40),
(61,	'tipo_grupo_id',	'Tipo grupo',	5,	'grupos.',	't',	'f',	51),
(60,	'label_campo_opcional1',	'Subdominio',	5,	'grupos.',	't',	'f',	50),
(63,	'tipo_asistente_id',	'Tipo asistente',	8,	'asistentes.',	't',	'f',	63),
(53,	'nombre_adulto_responsable',	'Nombre adulto responsable',	1,	'asistentes.',	'f',	't',	27),
(65,	'created_at',	'Fecha de creación',	1,	'asistentes.',	't',	'f',	49),
(23,	'informacion_opcional',	'Información opcional',	1,	'asistentes.',	't',	'f',	22),
(64,	'grupo_id',	'Grupo directo',	8,	'asistentes.',	't',	'f',	64),
(26,	'grupo_id',	'Grupo al que pertenece',	2,	'asistentes.',	'f',	'f',	39),
(66,	'usuario_creacion_id',	'Usuario creación',	1,	'asistentes.',	't',	'f',	49);

-- 2024-02-09 16:05:23.258583-06
